### ISSUE TITLE
Frontend development

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#74]
We can plan issues we want to tackle in the frontend here, which can be spun off into separate issues and PRs as time goes on, and following #69 and #41 being merged. Many of these issues are already present. If they can be handled individually just fine, we can close this issue

- [x] Add circuit editor -- #22 , #46
- [x] Finalize plaquette copying method and bug fixing -- #30
- [x] Compartmentalize server API calls -- #38

**Comment by smburdick** [comment]
We can close this with Gian's work on the circuit editor

**Comment by smburdick** [comment]
Moved to other threads.
